import { v4 as uuidv4 } from "uuid";
// "mediano"
export const animalSeeds = [
  // perdidos
  {
    id: uuidv4(),
    name: "Loki",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image:
      "https://cdn.pixabay.com/photo/2018/05/07/10/48/husky-3380548_960_720.jpg",
    comments: "un gran perro con pelo pincho!",
  },
  {
    id: uuidv4(),
    name: "Rex",
    specie: "perro",
    race: "otro",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image:
      "https://cdn.pixabay.com/photo/2017/12/29/10/47/animal-company-3047244__340.jpg",
    comments: "El mejor amigo de la casa",
  },
  {
    id: uuidv4(),
    name: "Roque",
    specie: "perro",
    race: "callejero",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image:
      "https://cdn.pixabay.com/photo/2016/10/15/12/01/dog-1742295__340.jpg",
    comments: "Es un amor y en casa lo extrañamos mucho",
  },
  {
    id: uuidv4(),
    name: "Chalita",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "hembra",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image:
      "https://cdn.pixabay.com/photo/2017/07/31/21/15/dog-2561134__340.jpg",
    comments: "un ovejero aleman",
  },
  {
    id: uuidv4(),
    name: "Blaky",
    specie: "perro",
    race: "labrador",
    age: "viejo",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image:
      "https://cdn.pixabay.com/photo/2016/11/01/10/29/dog-1787835__340.jpg",
    comments: "tenía puesto un collar verde",
  },
  {
    id: uuidv4(),
    name: "Colorado",
    specie: "gato",
    race: "otro",
    age: "adulto",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    // image:  "https://media.taringa.net/knn/fit:550/Z3M6Ly9rbjMvdGFyaW5nYS9DL0YvNy8wLzIvRC9Ccm9ueV9UYXJpbmd1ZXJvLzgwRC5qcGc",
    comments: "gato colorado muy vago",
  },
  {
    id: uuidv4(),
    name: "Lalo",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://cdn.pixabay.com/photo/2015/06/17/21/47/dog-813103__340.jpg",
    comments: "Lalo está medio loco pero es bueno",
  },
  {
    id: uuidv4(),
    name: "Matilda",
    specie: "perro",
    race: "mestizo",
    age: "joven",
    gender: "hembra",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image:
      "https://cdn.pixabay.com/photo/2017/10/02/21/56/dog-2810484__340.jpg",
    comments:
      "Matilda estaba muy vueltera el otro día en la plaza y despues no la vimos más :(",
  },
  {
    id: uuidv4(),
    name: "Toti",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments:
      "Toti no aparece por casa hace días y no tenemos fotos. Es alto y todo negro",
  },
  {
    id: uuidv4(),
    name: "Lali",
    specie: "perro",
    race: "callejero",
    age: "viejo",
    gender: "hembra",
    status: "perdido",
    vaccinationSchemeStatus: "incompleto",
    image: "https://cdn.pixabay.com/photo/2014/04/05/11/40/dog-316598__340.jpg",
    comments: "un ovejero aleman",
  },
  {
    id: uuidv4(),
    name: "chorizo",
    specie: "perro",
    race: "salchicha",
    age: "joven",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "incompleto",
    comments: "largo como salchicha",
    image:
      "https://i.pinimg.com/736x/57/cf/98/57cf9899961fb683a2dbb0b37fa3cd42--fat-animals-dog-facts.jpg",
  },
  {
    id: uuidv4(),
    name: "Alfajor",
    specie: "perro",
    race: "pitbull",
    age: "joven",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "se come un alfajor de un bocado",
    image:
      "https://static.misionesonline.news/wp-content/uploads/2021/09/19-17.jpg",
  },
  {
    id: uuidv4(),
    name: "pachorra",
    specie: "perro",
    race: "caniche toy",
    age: "joven",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "muy pachorra, lo encontraron durmiendo",
    image:
      "https://www.caracteristicas.co/wp-content/uploads/2017/02/perro-3-e1561679226953.jpg",
  },
  {
    id: uuidv4(),
    name: "lyzzie",
    specie: "perro",
    race: "caniche toy",
    age: "adulto",
    gender: "hembra",
    status: "encontrado",
    vaccinationSchemeStatus: "incompleto",
    comments: "solamente lyzzie",
    // image: "https://www.muyinteresante.es/mascotas/fotos/impresionantes-curiosidades-sobre-perros-que-fuerte",
  },
  {
    id: uuidv4(),
    name: "Tommy shelby",
    specie: "perro",
    race: "mestizo",
    age: "adulto",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "incompleto",
    comments: "lider de una banda de perros callejeros de londres",
    image:
      "https://statics.memondo.com/p/s1/crs/2020/06/CR_1147259_4527b033a6744dd9a6d0e0fd1ca164b3_pug_blinders_thumb_fb.jpg?cb=46469",
  },
  {
    id: uuidv4(),
    name: "bryan",
    specie: "perro",
    race: "mestizo",
    age: "adulto",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "suele romper via publica",
    image:
      "https://cdn.upsocl.com/wp-content/uploads/2021/08/iyesvm3s28e51.jpg",
  },
  {
    id: uuidv4(),
    name: "Marge",
    specie: "perro",
    race: "mastín napolitano",
    // age: "mediano",
    gender: "hembra",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "tiene un pelaje particular",
    image:
      "https://i.pinimg.com/550x/7e/5c/cd/7e5ccd8af43f4f7ceb2618ecf57f67bc.jpg",
  },
  {
    id: uuidv4(),
    name: "maira",
    specie: "gato",
    race: "bengala",
    age: "adulto",
    gender: "hembra",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "muy arizca",
    image:
      "https://2.bp.blogspot.com/-RKxVXO2Kfbo/V7wmJsvWcXI/AAAAAAAABF4/v_cSlNuZWQ0poZvvS56B1VrVnJ1FOlYzwCLcB/s1600/Gato%2Bbengala%2B1.jpg",
  },
  {
    id: uuidv4(),
    name: "Roco",
    specie: "perro",
    race: "boxer",
    age: "adulto",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "incompleto",
    image:
      "https://i.pinimg.com/originals/75/5c/14/755c14e0a51ffd6abfe80a048d9e04d7.jpg",
    comments:
      "un boxer super amable y bien criado, responde al nombre de Roco, sabemos que es viejito pero nos vamos de viaje y necesitamos ponerlo en adopcion en una famila que lo quiera",
  },
  {
    id: uuidv4(),
    name: "Esteban",
    specie: "otra especie",
    race: "Loro",
    age: "muy joven",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "incompleto",
    image: "https://c1.staticflickr.com/6/5016/5458097411_1d3d3df77c_b.jpg",
    comments: "lorito recien nacido",
  },
  {
    specie: "gato",
    race: "siámes",
    age: "joven",
    gender: "hembra",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image:
      "https://www.gatosiames.shop/wp-content/uploads/2020/10/gato-siames-2.jpg",
    comments:
      "gato hermoso recién nacido, no tiene nombre y tiene todas sus vacunas",
  },
  {
    id: uuidv4(),
    name: "daenerys",
    race: "otro",
    specie: "perro",
    age: "muy joven",
    gender: "hembra",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image:
      "https://nupec.com/wp-content/uploads/2020/07/Captura-de-pantalla-2020-07-24-a-las-17.33.44.png",
    comments:
      "Daenerys Stormborn of House Targaryen, the First of Her Name, Queen of the Andals and the First Men, Protector of the Seven Kingdoms",
  },
  {
    name: "Señor Gato",
    specie: "gato",
    race: "otro",
    age: "joven",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "incompleto",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c1/Cat_Sphynx._img_025.jpg",
    comments: "un gato arisco pero cariñoso",
  },
  {
    id: uuidv4(),
    specie: "perro",
    race: "ovejero",
    age: "desconocido",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    // image: "https://static.nationalgeographic.es/files/styles/image_3200/public/01-stray-dogs-nationalgeographic_1927666.jpg?w=1600&h=900",
    comments:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, veniam maxime nesciunt rem laborum quisquam amet expedita nisi fuga nam accusantium itaque at quaerat deserunt exercitationem, ea, deleniti sed numquam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae expedita repellat sint magni, at odit delectus unde, necessitatibus beatae consequatur est. Illum aut ad voluptatibus dolorum omnis aliquam tempora laborum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi beatae maiores ea iusto consequatur quod quasi id fuga explicabo tempora vitae, cumque, maxime laudantium odio natus amet ducimus, exercitationem nisi. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti, odit magni ipsa exercitationem consectetur in repellat aspernatur aliquam nostrum unde incidunt ut animi atque nobis consequuntur commodi eveniet at voluptatum! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nobis, esse in ratione qui eligendi cupiditate modi aperiam eos aliquam quas ullam culpa pariatur, molestiae exercitationem neque reprehenderit quae illo accusantium. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam dolores necessitatibus nihil numquam incidunt accusamus corrupti exercitationem neque ducimus veniam, consectetur hic ab ad facilis quaerat amet, perspiciatis similique rerum Quo porro illum quis, ea dolore hic libero excepturi nemo nam fugit minima totam voluptatum voluptatem odio reprehenderit sed. Sapiente voluptatibus incidunt rr adipisicing elit. Atque enim dolor rem vero? Quod inventore repudiandae maxime, quibusdam ipsa recusandae quis vitae hic, sit, ratione dolorem rem sequi! Esse, reiciendis. dio reprehenderit sed. Sapiente voluptatibus incidunt reprehenderit voluptatem hic corporis eaque aut eveniet sint Et quisquam sint iure illum delectus, ratione, impedit deserunt magni minus libero cupiditate porro inventore assumenda minima eveniet autem quis, debitis dolorum molestiae quibusdam voluptate eos! Dicta suscipit nemo atque! Lorem ipsum dolor, sit amet consectesssss ",
  },
  {
    name: "Flash",
    specie: "otra especie",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "incompleto",
    image:
      "https://t2.ea.ltmcdn.com/es/posts/3/7/4/la_tortuga_como_mascota_24473_orig.jpg",
    comments: "Tortuga super veloz lista para ser adoptada",
  },
  {
    id: uuidv4(),
    specie: "perro",
    race: "salchicha",
    age: "muy joven",
    gender: "hembra",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image:
      "https://mascotassaintdaniel.com/wp-content/uploads/2019/03/salchicha.jpg",
    comments: "perrita bebe hermosa super domesticada",
  },
  {
    name: "Michi",
    specie: "gato",
    race: "otro",
    age: "joven",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image:
      "https://www.huellascallejeras.com/wp-content/uploads/2020/10/jose-gato-adulto-en-adopcion-1-580x460.jpg",
    comments: "Gatito",
  },
  {
    name: "Hachiko",
    specie: "perro",
    race: "Sharpei",
    age: "desconocido",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "incompleto",
    image:
      "https://www.lavanguardia.com/files/content_image_mobile_filter/uploads/2020/07/28/5f2002eab1cef.jpeg",
    comments:
      "Hachiko está sentado en una estacion de tren esperando que lo adoptes!",
  },
  {
    id: uuidv4(),
    name: "Homero",
    specie: "perro",
    race: "pitbull",
    age: "adulto",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "rosquillas",
    image:
      "https://cnwebsite.blob.core.windows.net/files/2021/01/WhatsApp-Image-2021-01-15-at-13.49.25.jpeg",
  },
  {
    id: uuidv4(),
    name: "thor con commets muy largos",
    specie: "gato",
    race: "otro",
    age: "adulto",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "incompleto",
    comments:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, veniam maxime nesciunt rem laborum quisquam amet expedita nisi fuga nam accusantium itaque at quaerat deserunt exercitationem, ea, deleniti sed numquam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae expedita repellat sint magni, at odit delectus unde, necessitatibus beatae consequatur est. Illum aut ad voluptatibus dolorum omnis aliquam tempora laborum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi beatae maiores ea iusto consequatur quod quasi id fuga explicabo tempora vitae, cumque, maxime laudantium odio natus amet ducimus, exercitationem nisi. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Corrupti, odit magni ipsa exercitationem consectetur in repellat aspernatur aliquam nostrum unde incidunt ut animi atque nobis consequuntur commodi eveniet at voluptatum! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nobis, esse in ratione qui eligendi cupiditate modi aperiam eos aliquam quas ullam culpa pariatur, molestiae exercitationem neque reprehenderit quae illo accusantium. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam dolores necessitatibus nihil numquam incidunt accusamus corrupti exercitationem neque ducimus veniam, consectetur hic ab ad facilis quaerat amet, perspiciatis similique rerum Quo porro illum quis, ea dolore hic libero excepturi nemo nam fugit minima totam voluptatum voluptatem odio reprehenderit sed. Sapiente voluptatibus incidunt reprehenderit voluptatem hic corporis eaque aut eveniet sint Et quisquam sint iure illum delectus, ratione, impedit deserunt magni minus libero cupiditate porro inventore assumenda minima eveniet autem quis, debitis dolorum molestiae quibusdam voluptate eos! Dicta suscipit nemo atque! Lorem ipsum dolor, sit amet consectetptatem id aliquid perferendis! Vitae amet ratione temporibus perferendis. Ullam, accusantium Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque neque nemo quo magni qui voluptatem quidem esse dolor, consequatur voluptatum veritatis deserunt incidunt voluptate reiciendis sequi, totam repudiandae, beatae omnis? Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque illo, repellat consequatur sit unde ab consectetur. Perspiciatis temporibus vel delectus vero quas ipsum totam eum recusandae mollitia quibusdam. Delectus, explicabo. Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque enim dolor rem vero? Quod inventore repudiandae maxime, quibusdam ipsa recusandae quis vitae hic, sit, ratione dolorem rem sequi! Esse, reiciendis. dio reprehenderit sed. Sapiente voluptatibus incidunt reprehenderit voluptatem hic corporis eaque aut eveniet sint Et quisquam sint iure illum delectus, ratione, impedit deserunt magni minus libero cupiditate porro inventore assumenda minima eveniet autem quis, debitis dolorum molestiae quibusdam voluptate eos! Dicta suscipit nemo atque! Lorem ipsum dolor, sit amet consectesssss ",
    image:
      "https://i.pinimg.com/originals/1a/94/86/1a948614d9f9d3e6dc4b6b742b86c730.jpg",
  },
  {
    id: uuidv4(),
    name: "thor",
    specie: "gato",
    race: "otro",
    age: "adulto",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "incompleto",
    comments: "es muy rapido",
    image:
      "https://i.pinimg.com/originals/1a/94/86/1a948614d9f9d3e6dc4b6b742b86c730.jpg",
  },
  {
    id: uuidv4(),
    name: "superman",
    specie: "perro",
    race: "pitbull",
    age: "adulto",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "puede volar",
    // image:
    //   "https://images.unsplash.com/photo-1532202802379-df93d543bac3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZGlzZnJheiUyMGRlJTIwcGVycm98ZW58MHx8MHx8&w=1000&q=80",
  },
  {
    id: uuidv4(),
    name: "akita trump",
    specie: "perro",
    race: "akita",
    age: "adulto",
    gender: "macho",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "dueño de un hotel de perros",
    image:
      "https://viapais.com.ar/resizer/TXjDSl_CamriDPdbL6RWFLJ8ZQ8=/1023x663/smart/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/G5SDIZJYMIYTAMRZGU4TANJXGM.jpg",
  },
  {
    id: uuidv4(),
    name: "Mufasa",
    specie: "perro",
    race: "pitbull",
    age: "adulto",
    gender: "hembra",
    status: "encontrado",
    vaccinationSchemeStatus: "completo",
    comments: "rey de las croquetas",
    image:
      "https://www.schnauzi.com/wp-content/uploads/2012/01/perro-disfraz-leon.jpg",
  },
];
