import { v4 as uuidv4 } from "uuid";

export const petTS = [
  {
    id: uuidv4(),
    name: "LOKIII",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un gran perro con pelo pincho!",
  },
  {
    id: uuidv4(),
    name: "REX",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un ovejero aleman",
  },
  {
    // id: uuidv4(),
    name: "UNO SIN ID",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un ovejero aleman",
  },
  {
    // id: 1,
    // name: undefined,
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un ovejero aleman",
  },
  {
    // id: uuidv4(),
    name: "UNO SIN ID",
    specie: "perro",
    race: "labrador",
    age: "viejitooo",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un ovejero aleman",
  },

  {
    id: uuidv4(),
    name:"Roco",
    specie: "perro",
    race: "boxer",
    age: "adulto",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "incompleto",
    image: "https://i.pinimg.com/originals/75/5c/14/755c14e0a51ffd6abfe80a048d9e04d7.jpg",
    comments: "un boxer super amable y bien criado, responde al nombre de Roco, sabemos que es viejito pero nos vamos de viaje y necesitamos ponerlo en adopcion en una famila que lo quiera",
  },
  {
    name: "Esteban",
    specie: "otra especie",
    race: "Loro",
    age: "muy joven",
    gender: "macho",
    status:"en adopción",
    vaccinationSchemeStatus: "incompleto",
    image:"https://c1.staticflickr.com/6/5016/5458097411_1d3d3df77c_b.jpg",
    comments: "lorito recien nacido",
  },
  {
    specie: "gato",
    race: "siámes",
    age: "joven",
    gender: "hembra",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image:"https://www.gatosiames.shop/wp-content/uploads/2020/10/gato-siames-2.jpg",
    comments: "gato hermoso recién nacido, no tiene nombre y tiene todas sus vacunas",
  },
  {
    id:uuidv4(),
    name: "daenerys",
    specie: "perro",
    age: "muy joven",
    gender: "hembra",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image: "https://c8.alamy.com/compes/2ckecra/un-perro-posan-para-una-foto-vestida-como-daenerys-targaryen-del-juego-de-tronos-durante-el-24-desfile-anual-tompkins-square-halloween-dog-parade-en-nueva-york-25-de-octubre-de-2014-cientos-de-duenos-de-perros-visten-a-sus-perros-y-compiten-por-diversion-y-premios-durante-el-desfile-reuters-carlo-allegri-estados-unidos-tags-sociedad-animales-entretenimiento-2ckecra.jpg",
    comments: "Daenerys Stormborn of House Targaryen, the First of Her Name, Queen of the Andals and the First Men, Protector of the Seven Kingdoms",
  },
  {
    name: "Señor Gato",
    specie: "gato",
    age: "joven",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "incompleto",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Cat_Sphynx._img_025.jpg",
    comments: "un gato arisco pero cariñoso",
  },
  {
    id: uuidv4(),
    specie: "perro",
    race: "ovejero",
    age: "desconocido",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image:"https://static.nationalgeographic.es/files/styles/image_3200/public/01-stray-dogs-nationalgeographic_1927666.jpg?w=1600&h=900",
    comments: "perrito lleno de amor en busca de hogar",
  },
  {
    name: "Flash",
    specie: "otra especie",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "incompleto",
    image:"https://t2.ea.ltmcdn.com/es/posts/3/7/4/la_tortuga_como_mascota_24473_orig.jpg",
    comments: "Tortuga super veloz lista para ser adoptada",
  },
  {
    id: uuidv4(),
    specie: "perro",
    race: "salchicha",
    age: "muy joven",
    gender: "hembra",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image:"https://mascotassaintdaniel.com/wp-content/uploads/2019/03/salchicha.jpg",
    comments: "perrita bebe hermosa super domesticada",
  },
  {
    name: "Michi",
    specie: "gato",
    age: "joven",
    gender: "macho",
    status: "en adopción",
    vaccinationSchemeStatus: "completo",
    image:"https://www.huellascallejeras.com/wp-content/uploads/2020/10/jose-gato-adulto-en-adopcion-1-580x460.jpg",
    comments: "Gatito",
  },
  {
    name:"Hachiko",
    specie: "perro",
    race: "Sharpei",
    age: "desconocido",
    gender: "macho",
    status:"en adopción",
    vaccinationSchemeStatus: "incompleto",
    image: "https://www.lavanguardia.com/files/content_image_mobile_filter/uploads/2020/07/28/5f2002eab1cef.jpeg",
    comments: "Hachiko está sentado en una estacion de tren esperando que lo adoptes!",
  },
];