import { v4 as uuidv4 } from "uuid";

export const petTS = [
  // perdidos
  {
    id: uuidv4(),
    name: "Loki",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://cdn.pixabay.com/photo/2018/05/07/10/48/husky-3380548_960_720.jpg",
    comments: "un gran perro con pelo pincho!",
  },
  {
    id: uuidv4(),
    name: "Rex",
    specie: "perro",
    race: "otro",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://cdn.pixabay.com/photo/2017/12/29/10/47/animal-company-3047244__340.jpg",
    comments: "El mejor amigo de la casa",
  },
  {
    id: uuidv4(),
    name: "Roque",
    specie: "perro",
    race: "callejero",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://cdn.pixabay.com/photo/2016/10/15/12/01/dog-1742295__340.jpg",
    comments: "Es un amor y en casa lo extrañamos mucho",
  },
  {
    id: 1,
    name: "Chalita",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "hembra",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://cdn.pixabay.com/photo/2017/07/31/21/15/dog-2561134__340.jpg",
    comments: "un ovejero aleman",
  },
  {
    id: uuidv4(),
    name: "Blaky",
    specie: "perro",
    race: "labrador",
    age: "viejo",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://cdn.pixabay.com/photo/2016/11/01/10/29/dog-1787835__340.jpg",
    comments: "tenía puesto un collar verde",
  },
  {
    id: uuidv4(),
    name: "Colorado",
    specie: "gato",
    race: "otro",
    age: "adulto",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://media.taringa.net/knn/fit:550/Z3M6Ly9rbjMvdGFyaW5nYS9DL0YvNy8wLzIvRC9Ccm9ueV9UYXJpbmd1ZXJvLzgwRC5qcGc",
    comments: "gato colorado muy vago",
  },
  {
    id: uuidv4(),
    name: "Lalo",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://cdn.pixabay.com/photo/2015/06/17/21/47/dog-813103__340.jpg",
    comments: "Lalo está medio loco pero es bueno",
  },
  {
    id: uuidv4(),
    name: "Matilda",
    specie: "perro",
    race: "mestizo",
    age: "joven",
    gender: "hembra",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    image: "https://cdn.pixabay.com/photo/2017/10/02/21/56/dog-2810484__340.jpg",
    comments: "Matilda estaba muy vueltera el otro día en la plaza y despues no la vimos más :(",
  },
  {
    id: 55,
    name: "Toti",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "Toti no aparece por casa hace días y no tenemos fotos. Es alto y todo negro",
  },
  {
    id: uuidv4(),
    name: "Lali",
    specie: "perro",
    race: "callejero",
    age: "viejo",
    gender: "hembra",
    status: "perdido",
    vaccinationSchemeStatus: "incompleto",
    image: "https://cdn.pixabay.com/photo/2014/04/05/11/40/dog-316598__340.jpg",
    comments: "un ovejero aleman",
  }
];