import { v4 as uuidv4 } from "uuid";

export const petTS = [
  {
    id: uuidv4(),
    name: "LOKIII",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un gran perro con pelo pincho!",
  },
  {
    id: uuidv4(),
    name: "REX",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un ovejero aleman",
  },
  {
    // id: uuidv4(),
    name: "UNO SIN ID",
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un ovejero aleman",
  },
  {
    // id: 1,
    // name: undefined,
    specie: "perro",
    race: "labrador",
    age: "joven",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un ovejero aleman",
  },
  {
    // id: uuidv4(),
    name: "UNO SIN ID",
    specie: "perro",
    race: "labrador",
    age: "viejitooo",
    gender: "macho",
    status: "perdido",
    vaccinationSchemeStatus: "completo",
    comments: "un ovejero aleman",
  },
];